 services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - "{{ docker_dir }}/zigbee2mqtt/data:/app/data"
      - /run/udev:/run/udev:ro
      - /etc/ssl:/etc/ssl:ro
    ports:
      - 8080:8080
    environment:
      - TZ="{{ timezone }}"
    
  {% if zigbee_serial_device_port %}
    devices:
      - "{{ zigbee_serial_device_port }}:{{ zigbee_serial_device_port }}"
  {% endif %}